In [1]:
import pandas as pd

# 데이터 프레임 초기화

In [57]:
_df_cache = {}
_df_cache['df'] = pd.read_csv(r"D:\MCP2601\AgentWork\10_MCP서버개발\121_analytics\data.csv")
_df_cache['df']

        이름  나이        도시      키
0    Alice  25  New York  170.0
1      Bob  30    London    NaN
2  Charlie  28     Paris  175.0
3    David  35     Tokyo  168.0
4    Emily  27     Seoul    NaN
5  gildong  50     Seoul  175.0
6  gildong  50     Seoul  175.0

# 기본데이터 확인

In [ ]:
# 다음은 캐시에 저장된 데이터프레임에 대해 다양한 기본 정보
# (형태, 데이터 타입, 결측치 개수, 칼럼명, 요약 통계 등)를 조회할 수 있는 
# MCP 도구를 정의한 것입니다. 
# 사용자가 원하는 분석 종류를 operation 파라미터로 지정하면 
# 작업을 수행한 후 결과를 반환합니다. 
# 지원하지 않는 operation을 입력할 경우 에러가 발생합니다.

In [3]:
df = _df_cache['df']

In [4]:
df.shape

(7, 4)

In [5]:
df.dtypes

이름        str
나이      int64
도시        str
키     float64
dtype: object

In [7]:
df.isnull().sum()

이름    0
나이    0
도시    0
키     2
dtype: int64

In [8]:
df.columns

Index(['이름', '나이', '도시', '키'], dtype='str')

In [9]:
df.describe()

              나이           키
count   7.000000    5.000000
mean   35.000000  172.600000
std    10.708252    3.361547
min    25.000000  168.000000
25%    27.500000  170.000000
50%    30.000000  175.000000
75%    42.500000  175.000000
max    50.000000  175.000000

In [10]:
def basic_data_check(
    operation
):
    df = _df_cache['df']
    operations = {
        'shape': lambda: df.shape,
        'dtypes': lambda: df.dtypes,
        'missing': lambda: df.isnull().sum(),
        'columns': lambda: list(df.columns),
        'describe': lambda: df.describe(),
    }
    if operation not in operations:
        raise ValueError(f"💥Unsupported operation: {operation}")

    return operations[operation]()

In [11]:
basic_data_check('shape')

(7, 4)

In [12]:
basic_data_check('dtypes')

이름        str
나이      int64
도시        str
키     float64
dtype: object

In [13]:
basic_data_check('missing')

이름    0
나이    0
도시    0
키     2
dtype: int64

In [14]:
basic_data_check('columns')

['이름', '나이', '도시', '키']

In [15]:
basic_data_check('describe')

              나이           키
count   7.000000    5.000000
mean   35.000000  172.600000
std    10.708252    3.361547
min    25.000000  168.000000
25%    27.500000  170.000000
50%    30.000000  175.000000
75%    42.500000  175.000000
max    50.000000  175.000000

In [17]:
# basic_data_check('corr')

# 컬럼별 데이터 체크

In [ ]:
# 캐시에 저장된 데이터프레임에서 특정 칼럼을 대상으로 고윳값 목록이나 
# 값별 개수를 조회할 수 있는 MCP 도구입니다. 
# 사용자가 칼럼명과 원하는 분석 종류 (operation)를 입력하면 
# 해당 칼럼의 고윳값이나 각 값의 빈도수를 반환합니다. 
# 이를 통해 칼럼별 데이터 분포나 특성을 빠르게 확인할 수 있습니다. 
# 칼럼이 존재하지 않거나 지원하지 않는 operation을 입력할 경우 에러가 발생합니다.

In [18]:
df.columns

Index(['이름', '나이', '도시', '키'], dtype='str')

In [19]:
df

        이름  나이        도시      키
0    Alice  25  New York  170.0
1      Bob  30    London    NaN
2  Charlie  28     Paris  175.0
3    David  35     Tokyo  168.0
4    Emily  27     Seoul    NaN
5  gildong  50     Seoul  175.0
6  gildong  50     Seoul  175.0

In [22]:
list(df['도시'].unique())

['New York', 'London', 'Paris', 'Tokyo', 'Seoul']

In [23]:
df['도시'].value_counts()

도시
Seoul       3
New York    1
London      1
Paris       1
Tokyo       1
Name: count, dtype: int64

In [24]:
def column_data_check(
    operation,  # 'unique', 'value_counts'
    column
):
    df = _df_cache['df']

    if column not in df.columns:
        raise ValueError(f"💥Column '{column}' not found in Dataframe")

    operations = {
        "unique": lambda: list(df[column].unique()),
        "value_counts": lambda: df[column].value_counts()
    }

    if operation not in operations:
        raise ValueError(f"💥Unsupported operation: {operation}")

    return operations[operation]()

In [26]:
df

        이름  나이        도시      키
0    Alice  25  New York  170.0
1      Bob  30    London    NaN
2  Charlie  28     Paris  175.0
3    David  35     Tokyo  168.0
4    Emily  27     Seoul    NaN
5  gildong  50     Seoul  175.0
6  gildong  50     Seoul  175.0

In [25]:
column_data_check('unique', '나이')

[np.int64(25),
 np.int64(30),
 np.int64(28),
 np.int64(35),
 np.int64(27),
 np.int64(50)]

In [27]:
column_data_check('unique', '도시')

['New York', 'London', 'Paris', 'Tokyo', 'Seoul']

In [28]:
column_data_check('value_counts', '도시')

도시
Seoul       3
New York    1
London      1
Paris       1
Tokyo       1
Name: count, dtype: int64

In [31]:
# column_data_check('value_counts', 'ㅌㅌㅌ')
# column_data_check('ㅔㅔㅔㅔ', '도시')

# 데이터 전처리

In [ ]:
# 캐시에 저장된 데이터프레임에서 결측치 제거(dropna)나 
# 중복 행 제거(drop_duplicates) 같은 기본 전처리 작업을 수행하고, 
# 그 결과를 다시 캐시에 저장하는 MCP 도구입니다. 
# 사용자가 원하는 전처리 작업을 operation 파라미터로 지정하면 
# 해당 처리가 적용된 데이터프레임을 반환하며, 지원하지 않는 작업을 
# 입력할 경우 에러가 발생합니다.

In [32]:
df

        이름  나이        도시      키
0    Alice  25  New York  170.0
1      Bob  30    London    NaN
2  Charlie  28     Paris  175.0
3    David  35     Tokyo  168.0
4    Emily  27     Seoul    NaN
5  gildong  50     Seoul  175.0
6  gildong  50     Seoul  175.0

In [33]:
df.dropna()

        이름  나이        도시      키
0    Alice  25  New York  170.0
2  Charlie  28     Paris  175.0
3    David  35     Tokyo  168.0
5  gildong  50     Seoul  175.0
6  gildong  50     Seoul  175.0

In [34]:
df

        이름  나이        도시      키
0    Alice  25  New York  170.0
1      Bob  30    London    NaN
2  Charlie  28     Paris  175.0
3    David  35     Tokyo  168.0
4    Emily  27     Seoul    NaN
5  gildong  50     Seoul  175.0
6  gildong  50     Seoul  175.0

In [35]:
df.drop_duplicates()

        이름  나이        도시      키
0    Alice  25  New York  170.0
1      Bob  30    London    NaN
2  Charlie  28     Paris  175.0
3    David  35     Tokyo  168.0
4    Emily  27     Seoul    NaN
5  gildong  50     Seoul  175.0

In [36]:
def data_preprocess(
    operation  # "dropna", "drop_duplicates"
):
    df = _df_cache['df']
    operations = {
        'dropna': lambda: df.dropna(),
        'drop_duplicates': lambda: df.drop_duplicates(),
    }
    if operation not in operations:
        raise ValueError(f"💥Unsupported operation: {operation}")

    result = operations[operation]() 
    _df_cache['df'] = result  # 원본 변경.

    return result

In [37]:
df

        이름  나이        도시      키
0    Alice  25  New York  170.0
1      Bob  30    London    NaN
2  Charlie  28     Paris  175.0
3    David  35     Tokyo  168.0
4    Emily  27     Seoul    NaN
5  gildong  50     Seoul  175.0
6  gildong  50     Seoul  175.0

In [38]:
data_preprocess('dropna')

        이름  나이        도시      키
0    Alice  25  New York  170.0
2  Charlie  28     Paris  175.0
3    David  35     Tokyo  168.0
5  gildong  50     Seoul  175.0
6  gildong  50     Seoul  175.0

In [39]:
df = _df_cache['df']
df

        이름  나이        도시      키
0    Alice  25  New York  170.0
2  Charlie  28     Paris  175.0
3    David  35     Tokyo  168.0
5  gildong  50     Seoul  175.0
6  gildong  50     Seoul  175.0

In [40]:
data_preprocess('drop_duplicates')

        이름  나이        도시      키
0    Alice  25  New York  170.0
2  Charlie  28     Paris  175.0
3    David  35     Tokyo  168.0
5  gildong  50     Seoul  175.0

In [41]:
df = _df_cache['df']
df

        이름  나이        도시      키
0    Alice  25  New York  170.0
2  Charlie  28     Paris  175.0
3    David  35     Tokyo  168.0
5  gildong  50     Seoul  175.0

# 데이터 필터링

In [ ]:
# 캐시에 저장된 데이터프레임에서 특정 칼럼의 값이 입력한 조건값보다 
# 크거나 같거나, 작을 때 해당하는 행만 필터링해서 반환하는 MCP 도구입니다. 
# 사용자가 operation(예:filter_gt, filter_eq, filter_lt). 칼럼명, 
# 비굣값을 입력하면 조건에 맞는 데이터만 추출할 수 있습니다. 
# 칼럼값 기준으로 손쉽게 원하는 데이터만 골라낼 수 있습니다.

In [42]:
df

        이름  나이        도시      키
0    Alice  25  New York  170.0
2  Charlie  28     Paris  175.0
3    David  35     Tokyo  168.0
5  gildong  50     Seoul  175.0

In [45]:
df[df['키'] > 170.0]

        이름  나이     도시      키
2  Charlie  28  Paris  175.0
5  gildong  50  Seoul  175.0

In [46]:
df[df['나이'] < 30]

        이름  나이        도시      키
0    Alice  25  New York  170.0
2  Charlie  28     Paris  175.0

In [47]:
df[df['도시'] == 'Seoul']

        이름  나이     도시      키
5  gildong  50  Seoul  175.0

In [52]:
def col_data_analysis(
    operation,  # 'filter_gt', 'filter_eq', 'filter_lt'
    column,  # 필터링할 컬럼
    condition_value  # 비교할 값
):
    df = _df_cache['df']

    if column not in df.columns:
        raise ValueError(f"💥Column '{column}' not found in Dataframe")

    operations = {
        "filter_gt": lambda: df[df[column] > condition_value],
        "filter_eq": lambda: df[df[column] == condition_value],
        "filter_lt": lambda: df[df[column] < condition_value],
    }

    if operation not in operations:
        raise ValueError(f"💥Unsupported operation: {operation}")

    return operations[operation]()

In [53]:
df

        이름  나이        도시      키
0    Alice  25  New York  170.0
2  Charlie  28     Paris  175.0
3    David  35     Tokyo  168.0
5  gildong  50     Seoul  175.0

In [54]:
col_data_analysis('filter_gt', '나이', 30)

        이름  나이     도시      키
3    David  35  Tokyo  168.0
5  gildong  50  Seoul  175.0

In [55]:
col_data_analysis('filter_eq', '도시', 'Seoul')

        이름  나이     도시      키
5  gildong  50  Seoul  175.0

In [56]:
col_data_analysis('filter_lt', '키', 175)

      이름  나이        도시      키
0  Alice  25  New York  170.0
3  David  35     Tokyo  168.0

# 그룹기반 집계

In [ ]:
# 캐시에 저장된 데이터프레임을 지정한 칼럼으로 그룹화한 뒤, 
# 평균(mean), 최대 (max), 합계(sum), 개수(count) 같은 집계 연산을 수행해 
# 그 결과를 반환하는 MCP 도구입니다. 
# 사용자가 집계 연산 종류와 그룹화할 칼럼, 집계할 칼럼을 입력하면 
# 원하는 그룹별 통계결과를 얻을 수 있으므로 데이터의 그룹별 특성을 
# 쉽게 분석할 수 있도록 도와줍니다. 
# 지원하지 않는 집계 연산을 입력할 경우 에러가 발생합니다.

In [58]:
df = _df_cache['df']
df

        이름  나이        도시      키
0    Alice  25  New York  170.0
1      Bob  30    London    NaN
2  Charlie  28     Paris  175.0
3    David  35     Tokyo  168.0
4    Emily  27     Seoul    NaN
5  gildong  50     Seoul  175.0
6  gildong  50     Seoul  175.0

In [62]:
df.groupby('도시')['나이'].mean()

도시
London      30.000000
New York    25.000000
Paris       28.000000
Seoul       42.333333
Tokyo       35.000000
Name: 나이, dtype: float64

In [63]:
df.groupby('도시')['나이'].max()

도시
London      30
New York    25
Paris       28
Seoul       50
Tokyo       35
Name: 나이, dtype: int64

In [64]:
df.groupby('도시')['키'].count()

도시
London      0
New York    1
Paris       1
Seoul       2
Tokyo       1
Name: 키, dtype: int64

In [65]:
def group_data_analysis(
    operation,     # 'mean', 'max', 'sum', 'count'
    group_column,   # 그룹할 컬럼
    target_column,  # 집계적용할 컬럼
):
    df = _df_cache['df']

    if group_column not in df.columns:
        raise ValueError(f"💥Group Column '{group_column}' not found in Dataframe")

    if target_column not in df.columns:
        raise ValueError(f"💥Target Column '{target_column}' not found in Dataframe")

    operations = {
        "mean": lambda: df.groupby(group_column)[target_column].mean(),
        "max": lambda: df.groupby(group_column)[target_column].max(),
        "sum": lambda: df.groupby(group_column)[target_column].sum(),
        "count": lambda: df.groupby(group_column)[target_column].count(),
    }

    if operation not in operations:
        raise ValueError(f"💥Unsupported operation: {operation}")

    return operations[operation]()

In [66]:
df

        이름  나이        도시      키
0    Alice  25  New York  170.0
1      Bob  30    London    NaN
2  Charlie  28     Paris  175.0
3    David  35     Tokyo  168.0
4    Emily  27     Seoul    NaN
5  gildong  50     Seoul  175.0
6  gildong  50     Seoul  175.0

In [67]:
group_data_analysis('mean', '도시', '키')

도시
London        NaN
New York    170.0
Paris       175.0
Seoul       175.0
Tokyo       168.0
Name: 키, dtype: float64

In [68]:
group_data_analysis('count', '도시', '이름')

도시
London      1
New York    1
Paris       1
Seoul       3
Tokyo       1
Name: 이름, dtype: int64